fix

diff --git a/.github/workflows/linux_ci.yml b/.github/workflows/linux_ci.yml
--- a/.github/workflows/linux_ci.yml
+++ b/.github/workflows/linux_ci.yml
@@ -12,12 +12,13 @@ jobs:
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
-        
+
       - name: Set up Flutter
         uses: subosito/flutter-action@v2
         with:
           flutter-version: '3.27.4'
           channel: stable
+
       - run: |
           sudo apt-get update -y
           sudo apt-get install -y curl git unzip xz-utils zip libglu1-mesa
@@ -25,41 +26,32 @@ jobs:
 
       - name: Clone Repository
         run: git clone https://${{secrets.SECRET_KEY}}@github.com/punisher-303/ECHOPULS.git
-              
+
       - name: Install Dependencies
         run: cd ECHOPULS && flutter pub get
-            
+
       - name: Extract version from pubspec.yaml
-        shell: powershell
         run: |
-            $vLine = Select-String -Path pubspec.yaml -Pattern '^version:\s*(\S+)' | Select-Object -First 1
-            if (-not $vLine) { Write-Error 'version not found in pubspec.yaml'; exit 1 }
-            $ver = $vLine.Matches[0].Groups[1].Value.Split('+')[0]
-            echo "VERSION=$ver" >> $env:GITHUB_ENV
+          ver=$(grep -m1 -E '^version:\s*' ECHOPULS/pubspec.yaml | awk '{print $2}' | cut -d'+' -f1)
+          if [ -z "$ver" ]; then echo "version not found in pubspec.yaml"; exit 1; fi
+          echo "VERSION=$ver" >> $GITHUB_ENV
+
+      - name: Create .env file
+        run: echo "CLIENT_ID = XXXXX\nCLIENT_SECRET = XXXX EOF" > ECHOPULS/assets/.env
 
       - name: Build Linux App
-        run: cd ECHOPULS && flutter build linux --release --build-number ${{github.run_number}}
+        run: |
+          adjusted=$(( ${{ github.run_number }} + 121 ))
+          echo "ADJUSTED_RUN_NUMBER=$adjusted" >> $GITHUB_ENV
+          cd ECHOPULS && flutter build linux --release --build-number $adjusted
 
       - name: Zip Linux App
         run: |
           cd ECHOPULS/build/linux/x64/release/bundle
-          zip -r echo_pulse_linux_v4.5.5_dev+${{github.run_number}}.zip .
-        
-
+          zip -r echo_pulse_linux_v${{ env.VERSION }}+${{ env.ADJUSTED_RUN_NUMBER }}.zip .
 
       - name: Upload Artifacts Linux App
         uses: actions/upload-artifact@v4
         with:
-          name: echo_pulse_linux_dev
-          path: ECHOPULS/build/linux/x64/release/bundle/echo_pulse_linux_v4.5.5_dev+${{github.run_number}}.zip
-      
-      - name: Create Release
-        uses: ncipollo/release-action@v1
-        with:
-          artifacts: |
-            ECHOPULS/build/linux/x64/release/bundle/echo_pulse_linux_v4.5.5_dev+${{github.run_number}}.zip
-          tag: v$env:VERSION+78
-          token: ${{secrets.SECRET_KEY}}
-          allowUpdates: true
-          omitBody: true
-          prerelease: true
+          name: echo_pulse_linux
+          path: ECHOPULS/build/linux/x64/release/bundle/echo_pulse_linux_v${{ env.VERSION }}+${{ env.ADJUSTED_RUN_NUMBER }}.zip
